-- ============================================================
-- 03_address_abbreviation.sql
-- Creates and populates dbo.Address_Abbreviation.
--
-- Columns
--   Address_Part_Abbreviation  the token as it appears in raw address data
--   Address_Part               the canonical expanded form
--   Skip_At_Beginning          1 = this mapping should be skipped when the
--                              token is the first alphabetic token in the string
--                              (used to disambiguate e.g. "St" = Saint vs Street)
--
-- Run in: Registrations_DW
-- ============================================================

IF OBJECT_ID(N'dbo.Address_Abbreviation', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Address_Abbreviation (
        ID                         INT          NOT NULL IDENTITY(1,1) PRIMARY KEY,
        Address_Part_Abbreviation  VARCHAR(20)  NOT NULL,
        Address_Part               VARCHAR(100) NOT NULL,
        Skip_At_Beginning          BIT          NOT NULL DEFAULT 0
    );
    CREATE INDEX IX_AddrAbbrev ON dbo.Address_Abbreviation (Address_Part_Abbreviation);
END;
GO

-- Safe re-run: only insert rows not already present.
INSERT INTO dbo.Address_Abbreviation (Address_Part_Abbreviation, Address_Part, Skip_At_Beginning)
SELECT v.Abbrev, v.Full, v.Skip
FROM (VALUES

    -- --------------------------------------------------------
    -- Street suffixes  (Skip_At_Beginning = 1)
    -- These words mean a street type when NOT the first token.
    -- --------------------------------------------------------
    ('Aly',   'Alley',          1),
    ('Anx',   'Annex',          1),
    ('Arc',   'Arcade',         1),
    ('Ave',   'Avenue',         1),
    ('Byu',   'Bayou',          1),
    ('Bch',   'Beach',          1),
    ('Bnd',   'Bend',           1),
    ('Blf',   'Bluff',          1),
    ('Blfs',  'Bluffs',         1),
    ('Btm',   'Bottom',         1),
    ('Blvd',  'Boulevard',      1),
    ('Br',    'Branch',         1),
    ('Brg',   'Bridge',         1),
    ('Brk',   'Brook',          1),
    ('Brks',  'Brooks',         1),
    ('Bg',    'Burg',           1),
    ('Bgs',   'Burgs',          1),
    ('Byp',   'Bypass',         1),
    ('Cp',    'Camp',           1),
    ('Cyn',   'Canyon',         1),
    ('Cpe',   'Cape',           1),
    ('Cswy',  'Causeway',       1),
    ('Ctr',   'Center',         1),
    ('Ctrs',  'Centers',        1),
    ('Cir',   'Circle',         1),
    ('Cirs',  'Circles',        1),
    ('Clf',   'Cliff',          1),
    ('Clfs',  'Cliffs',         1),
    ('Clb',   'Club',           1),
    ('Cmn',   'Common',         1),
    ('Cmns',  'Commons',        1),
    ('Cor',   'Corner',         1),
    ('Cors',  'Corners',        1),
    ('Crse',  'Course',         1),
    ('Ct',    'Court',          1),
    ('Cts',   'Courts',         1),
    ('Cv',    'Cove',           1),
    ('Cvs',   'Coves',          1),
    ('Crk',   'Creek',          1),
    ('Cres',  'Crescent',       1),
    ('Crst',  'Crest',          1),
    ('Xing',  'Crossing',       1),
    ('Xrd',   'Crossroad',      1),
    ('Xrds',  'Crossroads',     1),
    ('Curv',  'Curve',          1),
    ('Dl',    'Dale',           1),
    ('Dm',    'Dam',            1),
    ('Dv',    'Divide',         1),
    ('Dr',    'Drive',          1),
    ('Drs',   'Drives',         1),
    ('Est',   'Estate',         1),
    ('Ests',  'Estates',        1),
    ('Expy',  'Expressway',     1),
    ('Ext',   'Extension',      1),
    ('Exts',  'Extensions',     1),
    ('Fall',  'Fall',           1),
    ('Fls',   'Falls',          1),
    ('Fry',   'Ferry',          1),
    ('Fld',   'Field',          1),
    ('Flds',  'Fields',         1),
    ('Flt',   'Flat',           1),
    ('Flts',  'Flats',          1),
    ('Frd',   'Ford',           1),
    ('Frds',  'Fords',          1),
    ('Frst',  'Forest',         1),
    ('Frg',   'Forge',          1),
    ('Frgs',  'Forges',         1),
    ('Frk',   'Fork',           1),
    ('Frks',  'Forks',          1),
    ('Ft',    'Fort',           1),
    ('Fwy',   'Freeway',        1),
    ('Gdn',   'Garden',         1),
    ('Gdns',  'Gardens',        1),
    ('Gtwy',  'Gateway',        1),
    ('Gln',   'Glen',           1),
    ('Glns',  'Glens',          1),
    ('Grn',   'Green',          1),
    ('Grns',  'Greens',         1),
    ('Grv',   'Grove',          1),
    ('Grvs',  'Groves',         1),
    ('Hbr',   'Harbor',         1),
    ('Hbrs',  'Harbors',        1),
    ('Hvn',   'Haven',          1),
    ('Hts',   'Heights',        1),
    ('Hwy',   'Highway',        1),
    ('Hl',    'Hill',           1),
    ('Hls',   'Hills',          1),
    ('Holw',  'Hollow',         1),
    ('Inlt',  'Inlet',          1),
    ('Is',    'Island',         1),
    ('Iss',   'Islands',        1),
    ('Isle',  'Isle',           1),
    ('Jct',   'Junction',       1),
    ('Jcts',  'Junctions',      1),
    ('Ky',    'Key',            1),
    ('Kys',   'Keys',           1),
    ('Knl',   'Knoll',          1),
    ('Knls',  'Knolls',         1),
    ('Lk',    'Lake',           1),
    ('Lks',   'Lakes',          1),
    ('Land',  'Land',           1),
    ('Lndg',  'Landing',        1),
    ('Ln',    'Lane',           1),
    ('Lgt',   'Light',          1),
    ('Lgts',  'Lights',         1),
    ('Lf',    'Loaf',           1),
    ('Lck',   'Lock',           1),
    ('Lcks',  'Locks',          1),
    ('Ldg',   'Lodge',          1),
    ('Loop',  'Loop',           1),
    ('Mall',  'Mall',           1),
    ('Mnr',   'Manor',          1),
    ('Mnrs',  'Manors',         1),
    ('Mdw',   'Meadow',         1),
    ('Mdws',  'Meadows',        1),
    ('Mews',  'Mews',           1),
    ('Ml',    'Mill',           1),
    ('Mls',   'Mills',          1),
    ('Msn',   'Mission',        1),
    ('Mtwy',  'Motorway',       1),
    ('Mt',    'Mount',          1),
    ('Mtn',   'Mountain',       1),
    ('Mtns',  'Mountains',      1),
    ('Nck',   'Neck',           1),
    ('Orch',  'Orchard',        1),
    ('Oval',  'Oval',           1),
    ('Opas',  'Overpass',       1),
    ('Park',  'Park',           1),
    ('Pkwy',  'Parkway',        1),
    ('Pass',  'Pass',           1),
    ('Psge',  'Passage',        1),
    ('Path',  'Path',           1),
    ('Pike',  'Pike',           1),
    ('Pne',   'Pine',           1),
    ('Pnes',  'Pines',          1),
    ('Pl',    'Place',          1),
    ('Pln',   'Plain',          1),
    ('Plns',  'Plains',         1),
    ('Plz',   'Plaza',          1),
    ('Pt',    'Point',          1),
    ('Pts',   'Points',         1),
    ('Prt',   'Port',           1),
    ('Prts',  'Ports',          1),
    ('Pr',    'Prairie',        1),
    ('Radl',  'Radial',         1),
    ('Ramp',  'Ramp',           1),
    ('Rnch',  'Ranch',          1),
    ('Rpd',   'Rapid',          1),
    ('Rpds',  'Rapids',         1),
    ('Rst',   'Rest',           1),
    ('Rdg',   'Ridge',          1),
    ('Rdgs',  'Ridges',         1),
    ('Riv',   'River',          1),
    ('Rd',    'Road',           1),
    ('Rds',   'Roads',          1),
    ('Rte',   'Route',          1),
    ('Row',   'Row',            1),
    ('Rue',   'Rue',            1),
    ('Run',   'Run',            1),
    ('Shl',   'Shoal',          1),
    ('Shls',  'Shoals',         1),
    ('Shr',   'Shore',          1),
    ('Shrs',  'Shores',         1),
    ('Skwy',  'Skyway',         1),
    ('Spg',   'Spring',         1),
    ('Spgs',  'Springs',        1),
    ('Spur',  'Spur',           1),
    ('Sq',    'Square',         1),
    ('Sqs',   'Squares',        1),
    ('Sta',   'Station',        1),
    ('Stra',  'Stravenue',      1),
    ('Strm',  'Stream',         1),
    ('St',    'Street',         1),
    ('Sts',   'Streets',        1),
    ('Smt',   'Summit',         1),
    ('Ter',   'Terrace',        1),
    ('Trwy',  'Throughway',     1),
    ('Trce',  'Trace',          1),
    ('Trak',  'Track',          1),
    ('Trfy',  'Trafficway',     1),
    ('Trl',   'Trail',          1),
    ('Tunl',  'Tunnel',         1),
    ('Tpke',  'Turnpike',       1),
    ('Upas',  'Underpass',      1),
    ('Un',    'Union',          1),
    ('Uns',   'Unions',         1),
    ('Vly',   'Valley',         1),
    ('Vlys',  'Valleys',        1),
    ('Via',   'Viaduct',        1),
    ('Vw',    'View',           1),
    ('Vws',   'Views',          1),
    ('Vlg',   'Village',        1),
    ('Vlgs',  'Villages',       1),
    ('Vl',    'Ville',          1),
    ('Vis',   'Vista',          1),
    ('Walk',  'Walk',           1),
    ('Wls',   'Wells',          1),
    ('Wy',    'Way',            1),
    ('Ways',  'Ways',           1),

    -- --------------------------------------------------------
    -- Directionals  (Skip_At_Beginning = 0 -- valid anywhere)
    -- --------------------------------------------------------
    ('N',    'North',           0),
    ('S',    'South',           0),
    ('E',    'East',            0),
    ('W',    'West',            0),
    ('NE',   'Northeast',       0),
    ('NW',   'Northwest',       0),
    ('SE',   'Southeast',       0),
    ('SW',   'Southwest',       0),

    -- --------------------------------------------------------
    -- Secondary unit designators  (Skip_At_Beginning = 0)
    -- --------------------------------------------------------
    ('Apt',  'Apartment',       0),
    ('Bldg', 'Building',        0),
    ('Dept', 'Department',      0),
    ('Fl',   'Floor',           0),
    ('Frnt', 'Front',           0),
    ('Hngr', 'Hangar',          0),
    ('Key',  'Key',             0),
    ('Lbby', 'Lobby',           0),
    ('Lot',  'Lot',             0),
    ('Lowr', 'Lower',           0),
    ('Ofc',  'Office',          0),
    ('Ph',   'Penthouse',       0),
    ('Pier', 'Pier',            0),
    ('Rear', 'Rear',            0),
    ('Rm',   'Room',            0),
    ('Side', 'Side',            0),
    ('Slip', 'Slip',            0),
    ('Spc',  'Space',           0),
    ('Stop', 'Stop',            0),
    ('Ste',  'Suite',           0),
    ('Trlr', 'Trailer',         0),
    ('Unit', 'Unit',            0),
    ('Uppr', 'Upper',           0),

    -- --------------------------------------------------------
    -- Prefix words  (Skip_At_Beginning = 0)
    -- St = Saint when first alpha token; Street when not.
    -- --------------------------------------------------------
    ('St',   'Saint',           0),
    ('Mt',   'Mount',           0),
    ('Ft',   'Fort',            0),

    -- --------------------------------------------------------
    -- Ordinals  1st through 200th
    -- --------------------------------------------------------
    ('1st',   'First',          0), ('2nd',   'Second',        0),
    ('3rd',   'Third',          0), ('4th',   'Fourth',        0),
    ('5th',   'Fifth',          0), ('6th',   'Sixth',         0),
    ('7th',   'Seventh',        0), ('8th',   'Eighth',        0),
    ('9th',   'Ninth',          0), ('10th',  'Tenth',         0),
    ('11th',  'Eleventh',       0), ('12th',  'Twelfth',       0),
    ('13th',  'Thirteenth',     0), ('14th',  'Fourteenth',    0),
    ('15th',  'Fifteenth',      0), ('16th',  'Sixteenth',     0),
    ('17th',  'Seventeenth',    0), ('18th',  'Eighteenth',    0),
    ('19th',  'Nineteenth',     0), ('20th',  'Twentieth',     0),
    ('21st',  'Twenty First',   0), ('22nd',  'Twenty Second', 0),
    ('23rd',  'Twenty Third',   0), ('24th',  'Twenty Fourth', 0),
    ('25th',  'Twenty Fifth',   0), ('26th',  'Twenty Sixth',  0),
    ('27th',  'Twenty Seventh', 0), ('28th',  'Twenty Eighth', 0),
    ('29th',  'Twenty Ninth',   0), ('30th',  'Thirtieth',     0),
    ('31st',  'Thirty First',   0), ('32nd',  'Thirty Second', 0),
    ('33rd',  'Thirty Third',   0), ('34th',  'Thirty Fourth', 0),
    ('35th',  'Thirty Fifth',   0), ('36th',  'Thirty Sixth',  0),
    ('37th',  'Thirty Seventh', 0), ('38th',  'Thirty Eighth', 0),
    ('39th',  'Thirty Ninth',   0), ('40th',  'Fortieth',      0),
    ('41st',  'Forty First',    0), ('42nd',  'Forty Second',  0),
    ('43rd',  'Forty Third',    0), ('44th',  'Forty Fourth',  0),
    ('45th',  'Forty Fifth',    0), ('46th',  'Forty Sixth',   0),
    ('47th',  'Forty Seventh',  0), ('48th',  'Forty Eighth',  0),
    ('49th',  'Forty Ninth',    0), ('50th',  'Fiftieth',      0),
    ('51st',  'Fifty First',    0), ('52nd',  'Fifty Second',  0),
    ('53rd',  'Fifty Third',    0), ('54th',  'Fifty Fourth',  0),
    ('55th',  'Fifty Fifth',    0), ('56th',  'Fifty Sixth',   0),
    ('57th',  'Fifty Seventh',  0), ('58th',  'Fifty Eighth',  0),
    ('59th',  'Fifty Ninth',    0), ('60th',  'Sixtieth',      0),
    ('61st',  'Sixty First',    0), ('62nd',  'Sixty Second',  0),
    ('63rd',  'Sixty Third',    0), ('64th',  'Sixty Fourth',  0),
    ('65th',  'Sixty Fifth',    0), ('66th',  'Sixty Sixth',   0),
    ('67th',  'Sixty Seventh',  0), ('68th',  'Sixty Eighth',  0),
    ('69th',  'Sixty Ninth',    0), ('70th',  'Seventieth',    0),
    ('71st',  'Seventy First',  0), ('72nd',  'Seventy Second',0),
    ('73rd',  'Seventy Third',  0), ('74th',  'Seventy Fourth',0),
    ('75th',  'Seventy Fifth',  0), ('76th',  'Seventy Sixth', 0),
    ('77th',  'Seventy Seventh',0), ('78th',  'Seventy Eighth',0),
    ('79th',  'Seventy Ninth',  0), ('80th',  'Eightieth',     0),
    ('81st',  'Eighty First',   0), ('82nd',  'Eighty Second', 0),
    ('83rd',  'Eighty Third',   0), ('84th',  'Eighty Fourth', 0),
    ('85th',  'Eighty Fifth',   0), ('86th',  'Eighty Sixth',  0),
    ('87th',  'Eighty Seventh', 0), ('88th',  'Eighty Eighth', 0),
    ('89th',  'Eighty Ninth',   0), ('90th',  'Ninetieth',     0),
    ('91st',  'Ninety First',   0), ('92nd',  'Ninety Second', 0),
    ('93rd',  'Ninety Third',   0), ('94th',  'Ninety Fourth', 0),
    ('95th',  'Ninety Fifth',   0), ('96th',  'Ninety Sixth',  0),
    ('97th',  'Ninety Seventh', 0), ('98th',  'Ninety Eighth', 0),
    ('99th',  'Ninety Ninth',   0), ('100th', 'One Hundredth', 0),
    ('101st', 'One Hundred First',   0), ('102nd', 'One Hundred Second',  0),
    ('103rd', 'One Hundred Third',   0), ('104th', 'One Hundred Fourth',  0),
    ('105th', 'One Hundred Fifth',   0), ('106th', 'One Hundred Sixth',   0),
    ('107th', 'One Hundred Seventh', 0), ('108th', 'One Hundred Eighth',  0),
    ('109th', 'One Hundred Ninth',   0), ('110th', 'One Hundred Tenth',   0),
    ('111th', 'One Hundred Eleventh',  0), ('112th', 'One Hundred Twelfth',   0),
    ('113th', 'One Hundred Thirteenth',0), ('114th', 'One Hundred Fourteenth', 0),
    ('115th', 'One Hundred Fifteenth', 0), ('116th', 'One Hundred Sixteenth',  0),
    ('117th', 'One Hundred Seventeenth',0),('118th', 'One Hundred Eighteenth', 0),
    ('119th', 'One Hundred Nineteenth', 0),('120th', 'One Hundred Twentieth',  0),
    ('121st', 'One Hundred Twenty First',  0), ('122nd', 'One Hundred Twenty Second', 0),
    ('123rd', 'One Hundred Twenty Third',  0), ('124th', 'One Hundred Twenty Fourth',  0),
    ('125th', 'One Hundred Twenty Fifth',  0), ('126th', 'One Hundred Twenty Sixth',   0),
    ('127th', 'One Hundred Twenty Seventh',0), ('128th', 'One Hundred Twenty Eighth',  0),
    ('129th', 'One Hundred Twenty Ninth',  0), ('130th', 'One Hundred Thirtieth',      0),
    ('131st', 'One Hundred Thirty First',  0), ('132nd', 'One Hundred Thirty Second',  0),
    ('133rd', 'One Hundred Thirty Third',  0), ('134th', 'One Hundred Thirty Fourth',  0),
    ('135th', 'One Hundred Thirty Fifth',  0), ('136th', 'One Hundred Thirty Sixth',   0),
    ('137th', 'One Hundred Thirty Seventh',0), ('138th', 'One Hundred Thirty Eighth',  0),
    ('139th', 'One Hundred Thirty Ninth',  0), ('140th', 'One Hundred Fortieth',       0),
    ('141st', 'One Hundred Forty First',   0), ('142nd', 'One Hundred Forty Second',   0),
    ('143rd', 'One Hundred Forty Third',   0), ('144th', 'One Hundred Forty Fourth',   0),
    ('145th', 'One Hundred Forty Fifth',   0), ('146th', 'One Hundred Forty Sixth',    0),
    ('147th', 'One Hundred Forty Seventh', 0), ('148th', 'One Hundred Forty Eighth',   0),
    ('149th', 'One Hundred Forty Ninth',   0), ('150th', 'One Hundred Fiftieth',       0),
    ('151st', 'One Hundred Fifty First',   0), ('152nd', 'One Hundred Fifty Second',   0),
    ('153rd', 'One Hundred Fifty Third',   0), ('154th', 'One Hundred Fifty Fourth',   0),
    ('155th', 'One Hundred Fifty Fifth',   0), ('156th', 'One Hundred Fifty Sixth',    0),
    ('157th', 'One Hundred Fifty Seventh', 0), ('158th', 'One Hundred Fifty Eighth',   0),
    ('159th', 'One Hundred Fifty Ninth',   0), ('160th', 'One Hundred Sixtieth',       0),
    ('161st', 'One Hundred Sixty First',   0), ('162nd', 'One Hundred Sixty Second',   0),
    ('163rd', 'One Hundred Sixty Third',   0), ('164th', 'One Hundred Sixty Fourth',   0),
    ('165th', 'One Hundred Sixty Fifth',   0), ('166th', 'One Hundred Sixty Sixth',    0),
    ('167th', 'One Hundred Sixty Seventh', 0), ('168th', 'One Hundred Sixty Eighth',   0),
    ('169th', 'One Hundred Sixty Ninth',   0), ('170th', 'One Hundred Seventieth',     0),
    ('171st', 'One Hundred Seventy First', 0), ('172nd', 'One Hundred Seventy Second', 0),
    ('173rd', 'One Hundred Seventy Third', 0), ('174th', 'One Hundred Seventy Fourth', 0),
    ('175th', 'One Hundred Seventy Fifth', 0), ('176th', 'One Hundred Seventy Sixth',  0),
    ('177th', 'One Hundred Seventy Seventh',0),('178th', 'One Hundred Seventy Eighth', 0),
    ('179th', 'One Hundred Seventy Ninth', 0), ('180th', 'One Hundred Eightieth',      0),
    ('181st', 'One Hundred Eighty First',  0), ('182nd', 'One Hundred Eighty Second',  0),
    ('183rd', 'One Hundred Eighty Third',  0), ('184th', 'One Hundred Eighty Fourth',  0),
    ('185th', 'One Hundred Eighty Fifth',  0), ('186th', 'One Hundred Eighty Sixth',   0),
    ('187th', 'One Hundred Eighty Seventh',0), ('188th', 'One Hundred Eighty Eighth',  0),
    ('189th', 'One Hundred Eighty Ninth',  0), ('190th', 'One Hundred Ninetieth',      0),
    ('191st', 'One Hundred Ninety First',  0), ('192nd', 'One Hundred Ninety Second',  0),
    ('193rd', 'One Hundred Ninety Third',  0), ('194th', 'One Hundred Ninety Fourth',  0),
    ('195th', 'One Hundred Ninety Fifth',  0), ('196th', 'One Hundred Ninety Sixth',   0),
    ('197th', 'One Hundred Ninety Seventh',0), ('198th', 'One Hundred Ninety Eighth',  0),
    ('199th', 'One Hundred Ninety Ninth',  0), ('200th', 'Two Hundredth',              0)

) v (Abbrev, Full, Skip)
WHERE NOT EXISTS (
    SELECT 1 FROM dbo.Address_Abbreviation a
    WHERE  a.Address_Part_Abbreviation = v.Abbrev
      AND  a.Address_Part              = v.Full
);
GO
